name: 🐞 Bug report
description: File a bug/issue
title: "[BUG] <title>"
labels: [ "bug" ]
assignees:
  - pereyrarg11
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Please provide us your environment details!
  - type: dropdown
    id: app_version
    attributes:
      label: App version
      description: What version of our app are you running?
      options:
        - 1.0.0 (Latest)
        - Not listed here
      default: 0
    validations:
      required: true
  - type: dropdown
    id: sdk_version
    attributes:
      label: Android version
      description: What Android version (API level) do you have?
      options:
        - Android 7.0 (API level 24)
        - Android 7.1 (API level 25)
        - Android 8.0 (API level 26)
        - Android 8.1 (API level 27)
        - Android 9 (API level 28)
        - Android 10 (API level 29)
        - Android 11 (API level 30)
        - Android 12 (API level 31)
        - Android 12L (API level 32)
        - Android 13 (API level 33)
        - Android 14 (API level 34)
        - Not listed here
      default: 9
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Describe the behavior in order to understand what is happening
  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Open the app and navigate to...
        2. Scroll to...
        3. Click on...
    validations:
      required: true
  - type: textarea
    id: attachments
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
