name: 🚀 Feature request
description: Suggest an idea
title: "[FEATURE] <title>"
labels: [ "enhancement" ]
assignees:
  - pereyrarg11
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Brief explanation of the feature.
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Basic example
      description: Describe a basic example; attach screenshots or links here.
    validations:
      required: false
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why are we doing this? What use cases does it support? What is the expected outcome?
    validations:
      required: false
