name: Static code analysis

on:
  pull_request:
    branches: [ "develop", "main" ]
    types: [ "opened", "synchronize", "reopened", "ready_for_review"]

jobs:
  build:
    name: Detekt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get environment ready
        uses: ./.github/actions/setup-env

      - name: Decrypt repo
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        with:
          GIT_CRYPT_KEY: "${{ secrets.GIT_CRYPT_KEY }}"

      - name: Run Detekt
        run: ./gradlew detekt
